# GENERATED by build.tcl -period 6.667 -- do not edit.
# Source: fpga/constraints.xdc with clk_period rewritten.
# ---------------------------------------------------------------------------
# constraints.xdc --- timing constraints for conv_top.
#
# Owner : WP5.  Ref: docs/06_implementation_flow.md s1 and s2.
#
# Used for the out-of-context core builds that produce the FoM numbers, and for
# the board-demo implementation when that lands.
#
# CLOCK TARGET
#   150 MHz (6.667 ns). docs/06 s2 starts at 125 MHz and says to try 150 only
#   once there is >= 0.5 ns of margin; Phase 6 begins at 150 directly and lets
#   the measurement decide. The REPORTED Fmax must come from a clean run at the
#   constraint that closed -- never from extrapolating a negative slack.
#
#   `fpga/build.tcl -period <ns>` overrides this for the closure sweep. The
#   override re-applies the I/O delays too, because they are a fraction of the
#   period; the build log prints whatever it actually used.
#
# I/O DELAYS ARE DECLARED, DELIBERATELY
#   An out-of-context build leaves ports unconstrained unless told otherwise,
#   and an unconstrained port contributes no path to the timing report. Fmax
#   measured that way describes only register-to-register logic and silently
#   ignores everything entering or leaving the core -- a flattering number that
#   would not survive integration. Every input except the clock, and every
#   output, therefore carries a delay budget.
#
#   The budget is 20% of the clock period at each boundary, leaving 60% for the
#   core itself. That split is a convention, not a measurement: there is no
#   board-level timing model to derive it from yet, so it is stated here rather
#   than hidden, and it is identical for both variants so the LUT-vs-DSP
#   comparison stays fair.
# ---------------------------------------------------------------------------
set clk_period 6.667
set io_fraction 0.20
set io_budget [expr {$clk_period * $io_fraction}]

create_clock -period $clk_period -name clk [get_ports clk]

# All inputs except the clock itself. `remove_from_collection` is not permitted
# inside an XDC, so the clock is excluded with a name filter instead.
set_input_delay  -clock clk $io_budget [get_ports -filter {DIRECTION == IN && NAME != clk}]
set_output_delay -clock clk $io_budget [get_ports -filter {DIRECTION == OUT}]

# ---------------------------------------------------------------------------
# Reset: asynchronously asserted, synchronously deasserted (assumption A8).
# The assert edge is not a timed path into the fabric, and a reset fanning out
# to every flop would otherwise dominate the report and hide the real critical
# path -- which docs/06 s2 expects to be adder_tree stage 3 or a LUT multiplier.
# ---------------------------------------------------------------------------
set_false_path -from [get_ports rst_n]

# ---------------------------------------------------------------------------
# SRL mapping is NOT constrained here.
#
# An XDC is a constraint file, not general Tcl, and SRL_STYLE has to influence
# MAPPING -- applying it to already-synthesised cells would be too late. The
# mechanism that works is the (* srl_style = "srl" *) attribute in
# rtl/line_window.sv; the mechanism that ENFORCES the outcome is the compliance
# gate in build.tcl, which errors the build out if the default build ever
# reports BRAM != 0 or DSP != 0, plus the SRL count recorded in summary.txt as
# positive evidence that the delay lines really did map to shift registers.
# ---------------------------------------------------------------------------

