# ---------------------------------------------------------------------------
# fom.tcl --- Figure of Merit worksheet generator (Phase 6 / WP5).
#
# Ref: docs/06_implementation_flow.md s5 (worksheet) and s6 (variant comparison),
#      docs/00_charter.md (the FoM definition and why the design is shaped this
#      way).
#
#   FoM = Throughput / (Power x (LUTs + 50 x DSPs + 100 x BRAMs))
#
# Reads the per-variant summary.txt written by build.tcl plus the power number,
# and writes fpga/reports/fom.md. Run AFTER build.tcl, and after power_saif.tcl
# if a SAIF-based power figure is available.
#
#   vivado -mode batch -source fpga/fom.tcl
#
# HONESTY RULE BUILT IN: the worksheet records WHICH power methodology produced
# each number. docs/06 s4 requires vector-based post-implementation dynamic
# power from a real image frame for the REPORTED FoM; a vectorless figure is
# marked as provisional and the file says so in the output, so a provisional
# number can never be quoted in the report as if it were the real one.
# ---------------------------------------------------------------------------

set script_dir [file dirname [file normalize [info script]]]
set root       [file dirname $script_dir]
set reports    [file join $root fpga reports]

proc read_summary {path} {
    set d [dict create]
    if {![file exists $path]} { return $d }
    set fh [open $path r]
    while {[gets $fh line] >= 0} {
        set line [string trim $line]
        if {$line eq ""} { continue }
        set key [lindex $line 0]
        set val [string trim [string range $line [string length $key] end]]
        dict set d $key $val
    }
    close $fh
    return $d
}

# Pull total and dynamic on-chip power out of a report_power text report.
proc read_power {path} {
    set res [dict create total "" dynamic "" static "" confidence ""]
    if {![file exists $path]} { return $res }
    set fh [open $path r]
    while {[gets $fh line] >= 0} {
        if {[regexp {Total On-Chip Power \(W\)\s*\|\s*([0-9.]+)} $line -> v]} {
            dict set res total $v
        } elseif {[regexp {Dynamic \(W\)\s*\|\s*([0-9.]+)} $line -> v]} {
            dict set res dynamic $v
        } elseif {[regexp {Device Static \(W\)\s*\|\s*([0-9.]+)} $line -> v]} {
            dict set res static $v
        } elseif {[regexp {Confidence Level\s*\|\s*(\w+)} $line -> v]} {
            dict set res confidence $v
        }
    }
    close $fh
    return $res
}

set rows {}
foreach variant {lut dsp} {
    set vdir [file join $reports $variant]
    set sum  [read_summary [file join $vdir summary.txt]]
    if {[dict size $sum] == 0} {
        puts "SKIP $variant: no summary.txt (run build.tcl first)"
        continue
    }

    # Prefer the SAIF-based power report; fall back to vectorless and SAY SO.
    set saif_rpt [file join $vdir power_saif.rpt]
    set vl_rpt   [file join $vdir power_vectorless.rpt]
    if {[file exists $saif_rpt]} {
        set pw     [read_power $saif_rpt]
        set method "SAIF (vector-based, post-implementation, real frame)"
        set provisional 0
    } else {
        set pw     [read_power $vl_rpt]
        set method "VECTORLESS (PROVISIONAL -- not the docs/06 s4 methodology)"
        set provisional 1
    }

    set luts  [dict get $sum luts]
    set dsps  [dict get $sum dsps]
    set brams [dict get $sum brams]
    set cost  [expr {$luts + 50*$dsps + 100*$brams}]

    set pdyn [dict get $pw dynamic]
    set fom  "n/a"
    if {$pdyn ne "" && $pdyn > 0 && $cost > 0} {
        # Throughput is 1.0 output pixel per cycle by construction (docs/02 s8),
        # proven by the valid-count property in the regression.
        set fom [expr {1.0 / ($pdyn * $cost)}]
    }

    # Fmax from the achieved slack at the constrained period.
    set period [dict get $sum period_ns]
    set wns    [dict get $sum wns_ns]
    set fmax   "n/a"
    if {$wns ne "n/a" && $wns ne ""} {
        set fmax [expr {1000.0 / ($period - $wns)}]
    }

    lappend rows [list $variant $sum $pw $method $provisional $cost $fom $fmax]
}

if {[llength $rows] == 0} {
    error "fom.tcl: no variant summaries found under $reports -- run build.tcl first"
}

set out [file join $reports fom.md]
set fh [open $out w]
puts $fh "# Figure of Merit worksheet"
puts $fh ""
puts $fh "Generated by `vivado -mode batch -source fpga/fom.tcl`. Do not edit by hand."
puts $fh ""
puts $fh "    FoM = Throughput / (Power x (LUTs + 50 x DSPs + 100 x BRAMs))"
puts $fh ""
puts $fh "Throughput is **1.0 output pixel/cycle** by construction under continuous"
puts $fh "`px_valid` (docs/02_architecture.md s8). It is not measured from a"
puts $fh "wall-clock rate: the regression proves exactly (W-N+1)^2 qualified outputs"
puts $fh "per frame with no stall path anywhere in the datapath."
puts $fh ""

foreach row $rows {
    lassign $row variant sum pw method provisional cost fom fmax
    puts $fh "## Variant: `$variant` (USE_DSP=[dict get $sum use_dsp])"
    puts $fh ""
    puts $fh "| Quantity | Value | Source |"
    puts $fh "|---|---|---|"
    puts $fh "| Throughput T | 1.0 output px/cycle | architectural, regression-proven |"
    puts $fh "| LUTs | [dict get $sum luts] | `utilization.rpt` |"
    puts $fh "| Flip-flops | [dict get $sum ffs] | `utilization.rpt` |"
    puts $fh "| SRL primitives | [dict get $sum srls] | evidence of the SRL32 line-buffer mapping |"
    puts $fh "| DSPs | [dict get $sum dsps] | must be 0 for `lut` (build gate) |"
    puts $fh "| BRAMs | [dict get $sum brams] | must be 0 (build gate) |"
    puts $fh "| Dynamic power P | [dict get $pw dynamic] W | $method |"
    puts $fh "| Static power | [dict get $pw static] W | |"
    puts $fh "| Total on-chip power | [dict get $pw total] W | |"
    puts $fh "| Vivado confidence | [dict get $pw confidence] | |"
    puts $fh "| Cost = LUTs + 50xDSPs + 100xBRAMs | **$cost** | |"
    puts $fh "| **FoM = T / (P x Cost)** | **$fom** | |"
    puts $fh "| Constraint period | [dict get $sum period_ns] ns | `constraints.xdc` |"
    puts $fh "| WNS | [dict get $sum wns_ns] ns | `timing.rpt` |"
    puts $fh "| TNS | [dict get $sum tns_ns] ns | `timing.rpt` |"
    puts $fh "| Fmax estimate | $fmax MHz | 1000/(period - WNS) |"
    puts $fh ""
    if {$provisional} {
        puts $fh "> **PROVISIONAL POWER.** This FoM uses Vivado vectorless activity"
        puts $fh "> propagation, which docs/06_implementation_flow.md s4 explicitly"
        puts $fh "> rejects as not credible for the reported number. It must be"
        puts $fh "> replaced by a SAIF-based figure from a post-implementation"
        puts $fh "> simulation of a real image frame before this number goes in the"
        puts $fh "> report. Run `fpga/power_saif.tcl` once that SAIF exists."
        puts $fh ""
    }
}

puts $fh "## Notes on reading these numbers"
puts $fh ""
puts $fh "* Utilization comes from **out-of-context** synthesis, so it is the core"
puts $fh "  alone with no I/O buffers -- the honest number for a FoM that is about"
puts $fh "  the accelerator, not about a pin-out."
puts $fh "* Fmax is an estimate derived from achieved slack. The figure quoted in the"
puts $fh "  report must come from a clean run AT that constraint (docs/06 s2);"
puts $fh "  never report a frequency with WNS < 0."
puts $fh "* Because the FoM numerator is throughput **per cycle**, a higher Fmax buys"
puts $fh "  nothing in FoM -- it only improves absolute Mpx/s. That is the whole"
puts $fh "  reason the LUT variant is expected to win: 9 DSPs would add 450 to the"
puts $fh "  cost term for no numerator gain (docs/06 s6)."
close $fh

puts "wrote $out"
foreach row $rows {
    lassign $row variant sum pw method provisional cost fom fmax
    puts "FOM $variant: cost=$cost Pdyn=[dict get $pw dynamic] FoM=$fom Fmax=$fmax\
          [expr {$provisional ? {(PROVISIONAL POWER)} : {}}]"
}
